"""High-level MCP tools that compose the ``CbrClient`` with caching.

Each public function below corresponds to one MCP tool. They take primitive
arguments (``str``, ``date``, ``int``) so the JSON schema generated by FastMCP
stays compact, validate them through Pydantic adapters, and return the typed
response models from :mod:`schemas`.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import date, timedelta
from decimal import Decimal

from .cache import TTLCache
from .client import CbrClient
from .currency_codes import normalize_char_code
from .errors import CbrNotFoundError, CbrValidationError
from .schemas import (
    CurrencyRate,
    HistoryRates,
    InflationData,
    InflationPoint,
    KeyRateHistory,
    KeyRatePoint,
    MacroSnapshot,
    RatePoint,
)

logger = logging.getLogger(__name__)

DEFAULT_DAILY_TTL: float = 3600.0
DEFAULT_HISTORY_TTL: float = 86400.0
MAX_HISTORY_DAYS: int = 366


@dataclass(slots=True)
class ToolContext:
    """Bag of dependencies threaded through every tool call."""

    client: CbrClient
    daily_cache: TTLCache
    history_cache: TTLCache


def _coerce_date(value: date | str | None) -> date | None:
    """Accept either a ``date`` or an ISO ``YYYY-MM-DD`` string."""
    if value is None or isinstance(value, date):
        return value
    if isinstance(value, str):
        try:
            return date.fromisoformat(value)
        except ValueError as exc:
            raise CbrValidationError(f"invalid ISO date: {value!r}") from exc
    raise CbrValidationError(f"unsupported date value: {value!r}")


def _decimal(text: str) -> Decimal:
    return Decimal(text.replace(",", ".").strip())


async def get_rate(
    ctx: ToolContext,
    char_code: str,
    on_date: date | str | None = None,
) -> CurrencyRate:
    """Fetch the CBR quote for a single currency on the given (or latest) date."""
    canonical = normalize_char_code(char_code)
    target_date = _coerce_date(on_date)
    cache_key = f"daily:{canonical}:{target_date.isoformat() if target_date else 'latest'}"

    cached = await ctx.daily_cache.get(cache_key)
    if cached is not None:
        return cached  # type: ignore[no-any-return]

    raw = await ctx.client.fetch_currency_rate(canonical, on_date=target_date)
    nominal = int(raw.get("nominal") or 1)
    value = _decimal(raw["value"])
    vunit_text = raw.get("vunit_rate") or ""
    if vunit_text:
        vunit = _decimal(vunit_text)
    else:
        vunit = (value / nominal) if nominal else value

    quote_date = (
        date.fromisoformat(_iso_from_dotted(raw["date"]))
        if raw.get("date")
        else (target_date or date.today())
    )
    rate = CurrencyRate(
        char_code=canonical,
        num_code=raw.get("num_code", ""),
        name=raw.get("name", ""),
        nominal=nominal,
        value=value,
        vunit_rate=vunit,
        date=quote_date,
    )
    await ctx.daily_cache.set(cache_key, rate, ttl=DEFAULT_DAILY_TTL)
    return rate


async def history_rates(
    ctx: ToolContext,
    char_code: str,
    date_from: date | str,
    date_to: date | str,
) -> HistoryRates:
    """Fetch the CBR quote series for one currency between two dates inclusive."""
    canonical = normalize_char_code(char_code)
    df = _coerce_date(date_from)
    dt = _coerce_date(date_to)
    if df is None or dt is None:
        raise CbrValidationError("both date_from and date_to are required")
    if df > dt:
        raise CbrValidationError("date_from must be on or before date_to")
    if (dt - df).days > MAX_HISTORY_DAYS:
        raise CbrValidationError(
            f"requested range is too long (>{MAX_HISTORY_DAYS} days);"
            " call history_rates in shorter chunks"
        )

    cache_key = f"history:{canonical}:{df.isoformat()}:{dt.isoformat()}"
    cached = await ctx.history_cache.get(cache_key)
    if cached is not None:
        return cached  # type: ignore[no-any-return]

    name, raw_points = await ctx.client.fetch_history(canonical, df, dt)
    points: list[RatePoint] = []
    nominal = 1
    for raw in raw_points:
        try:
            point_date = date.fromisoformat(_iso_from_dotted(raw["date"]))
            value = _decimal(raw["value"])
            nominal = int(raw.get("nominal") or 1)
            vunit_text = raw.get("vunit_rate") or ""
            vunit = _decimal(vunit_text) if vunit_text else (value / nominal if nominal else value)
        except Exception:
            logger.debug("skipping malformed history record: %s", raw)
            continue
        points.append(RatePoint(date=point_date, value=value, vunit_rate=vunit))

    if not points:
        raise CbrNotFoundError(
            f"no history points returned for {canonical} between {df} and {dt}"
        )

    points.sort(key=lambda p: p.date)
    if name == canonical:
        try:
            latest = await ctx.client.fetch_currency_rate(canonical, on_date=None)
            name = latest.get("name") or canonical
        except Exception:
            name = canonical
    result = HistoryRates(
        char_code=canonical,
        name=name,
        nominal=nominal,
        date_from=df,
        date_to=dt,
        points=points,
    )
    await ctx.history_cache.set(cache_key, result, ttl=DEFAULT_HISTORY_TTL)
    return result


async def key_rate(
    ctx: ToolContext,
    date_from: date | str | None = None,
    date_to: date | str | None = None,
) -> KeyRateHistory:
    """Fetch the CBR key-rate series for the given range (default: last 30 days)."""
    dt = _coerce_date(date_to) or date.today()
    df = _coerce_date(date_from) or (dt - timedelta(days=30))
    if df > dt:
        raise CbrValidationError("date_from must be on or before date_to")
    if (dt - df).days > 365 * 5:
        raise CbrValidationError("key_rate range cannot exceed 5 years")

    cache_key = f"keyrate:{df.isoformat()}:{dt.isoformat()}"
    cached = await ctx.history_cache.get(cache_key)
    if cached is not None:
        return cached  # type: ignore[no-any-return]

    raw = await ctx.client.fetch_key_rate(df, dt)
    points: list[KeyRatePoint] = []
    for entry in raw:
        try:
            iso = entry["date"][:10]
            point_date = date.fromisoformat(iso)
            rate = _decimal(entry["rate"])
        except Exception:
            logger.debug("skipping malformed key-rate record: %s", entry)
            continue
        points.append(KeyRatePoint(date=point_date, rate=rate))

    points.sort(key=lambda p: p.date)
    result = KeyRateHistory(date_from=df, date_to=dt, points=points)
    await ctx.history_cache.set(cache_key, result, ttl=DEFAULT_HISTORY_TTL)
    return result


async def inflation(
    ctx: ToolContext,
    year_from: int | None = None,
    year_to: int | None = None,
) -> InflationData:
    """Fetch monthly year-over-year CPI inflation for the given year range."""
    today = date.today()
    if year_from is None:
        year_from = today.year - 1
    if year_to is None:
        year_to = today.year
    if year_from > year_to:
        raise CbrValidationError("year_from must be <= year_to")

    cache_key = "inflation:full"
    cached_all = await ctx.history_cache.get(cache_key)
    if cached_all is None:
        raw = await ctx.client.fetch_inflation()
        cached_all = raw
        await ctx.history_cache.set(cache_key, raw, ttl=DEFAULT_HISTORY_TTL)

    points: list[InflationPoint] = []
    for entry in cached_all:
        try:
            year = int(entry["year"])
            month = int(entry["month"])
            yoy_text = (entry.get("cpi_yoy_pct") or "").replace(",", ".").strip()
            yoy = Decimal(yoy_text) if yoy_text else None
        except Exception:
            continue
        if year < year_from or year > year_to:
            continue
        points.append(
            InflationPoint(year=year, month=month, cpi_yoy_pct=yoy, cpi_mom_pct=None)
        )

    points.sort(key=lambda p: (p.year, p.month))
    note = (
        "Source: cbr.ru/hd_base/infl/. CPI is measured as year-over-year change."
        if points
        else None
    )
    return InflationData(
        year_from=year_from,
        year_to=year_to,
        points=points,
        note=note,
    )


async def statistics(ctx: ToolContext) -> MacroSnapshot:
    """Return a compact macro snapshot: latest key rate, USD/EUR/CNY, inflation."""
    today = date.today()

    async def _safe_get_rate(code: str) -> Decimal | None:
        try:
            quote = await get_rate(ctx, code)
            return quote.vunit_rate
        except Exception as exc:
            logger.warning("statistics: cannot fetch %s rate: %s", code, exc)
            return None

    async def _safe_key_rate() -> Decimal | None:
        try:
            history = await key_rate(ctx)
            if history.points:
                return history.points[-1].rate
            return None
        except Exception as exc:
            logger.warning("statistics: cannot fetch key rate: %s", exc)
            return None

    async def _safe_inflation() -> tuple[Decimal | None, str | None]:
        try:
            data = await inflation(ctx, year_from=today.year - 1, year_to=today.year)
            if data.points:
                last = data.points[-1]
                return last.cpi_yoy_pct, f"{last.year:04d}-{last.month:02d}"
            return None, None
        except Exception as exc:
            logger.warning("statistics: cannot fetch inflation: %s", exc)
            return None, None

    usd = await _safe_get_rate("USD")
    eur = await _safe_get_rate("EUR")
    cny = await _safe_get_rate("CNY")
    kr = await _safe_key_rate()
    infl_pct, infl_period = await _safe_inflation()

    return MacroSnapshot(
        as_of=today,
        key_rate_pct=kr,
        usd_rate=usd,
        eur_rate=eur,
        cny_rate=cny,
        inflation_yoy_pct=infl_pct,
        inflation_period=infl_period,
    )


def _iso_from_dotted(raw: str) -> str:
    """Translate ``DD.MM.YYYY`` (with optional time) into ISO ``YYYY-MM-DD``."""
    text = raw.strip()
    if not text:
        return ""
    head = text.split("T", 1)[0]
    if "." in head:
        day, month, year = head.split(".")
        return f"{int(year):04d}-{int(month):02d}-{int(day):02d}"
    return head[:10]
